{{- if and .Values.serviceAccount.create (not .Values.sidecar.enabled) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "adaptr.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "adaptr.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
